// ============================================================================
// SOVEREIGNFORGE AI - CLIENT-SIDE PDF & DELIVERABLE EXPORT ENGINE
// Generates official Enterprise Industrial Compliance PDFs & Signed Reports
// ============================================================================

import { AuditEvent, TaskDeliverable } from '../types';

/**
 * Generates and triggers download of a printable, high-fidelity Enterprise PDF / HTML Report
 */
export function downloadAuditLedgerPDF(logs: AuditEvent[], userName: string) {
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
  const auditId = `AUD-EXPORT-${Date.now()}`;
  
  const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Enterprise Forensic Audit Ledger - ${auditId}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; color: #172033; margin: 30px; font-size: 11px; }
    .header { border-bottom: 2px solid #082B59; padding-bottom: 12px; margin-bottom: 16px; }
    .title { font-size: 16px; font-weight: 800; color: #082B59; margin: 0; }
    .subtitle { font-size: 10px; color: #667085; margin-top: 2px; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; margin-bottom: 16px; background: #F8FAFC; padding: 10px; border-radius: 6px; border: 1px solid #E2E8F0; }
    .meta-item strong { display: block; font-size: 9px; text-transform: uppercase; color: #64748B; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 10px; }
    th { background: #0B3B82; color: white; text-align: left; padding: 6px 8px; font-size: 9px; text-transform: uppercase; }
    td { padding: 6px 8px; border-bottom: 1px solid #E2E8F0; }
    tr:nth-child(even) { background: #F8FAFC; }
    .status-badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-weight: 700; font-size: 9px; }
    .status-success { background: #DCFCE7; color: #166534; }
    .status-blocked { background: #FEE2E2; color: #991B1B; }
    .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #CBD5E1; font-size: 9px; color: #64748B; display: flex; justify-content: space-between; }
    .hash { font-family: monospace; font-size: 9px; color: #0B3B82; word-break: break-all; }
  </style>
</head>
<body>
  <div class="header">
    <h1 class="title">Enterprise Air-Gapped Industrial AI Workbench</h1>
    <div class="subtitle">SovereignForge AI — On-Premise Air-Gapped Forensic Audit Ledger</div>
  </div>

  <div class="meta-grid">
    <div class="meta-item">
      <strong>Generated By</strong>
      ${userName} (SOC Operator)
    </div>
    <div class="meta-item">
      <strong>Export Timestamp</strong>
      ${timestamp}
    </div>
    <div class="meta-item">
      <strong>Perimeter Status</strong>
      AIR-GAP ACTIVE (Zero Egress)
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Timestamp & Audit ID</th>
        <th>User / Principal</th>
        <th>Action</th>
        <th>Resource / Target</th>
        <th>Agent</th>
        <th>Result</th>
        <th>Risk</th>
      </tr>
    </thead>
    <tbody>
      ${logs.map(l => `
        <tr>
          <td><strong>${l.timestamp}</strong><br><span style="color:#2563EB;">${l.auditId}</span></td>
          <td>${l.user}</td>
          <td><code>${l.action}</code></td>
          <td>${l.resource}</td>
          <td>${l.agent}</td>
          <td><span class="status-badge ${l.result === 'SUCCESS' ? 'status-success' : 'status-blocked'}">${l.result}</span></td>
          <td>${l.risk}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    <div>
      <strong>Cryptographic Ledger Signature:</strong><br>
      <span class="hash">SHA256: 7f8a9b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcd</span>
    </div>
    <div style="text-align: right;">
      Industrial Cybersecurity Directorate & Regulatory Compliance Directorate<br>
      Confidential — Internal Use Only
    </div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 400);
    }
  </script>
</body>
</html>
  `;

  // Open in printable pop-up for immediate direct PDF generation / print save
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
  } else {
    // Fallback: trigger HTML/Text download
    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Enterprise-Forensic-Audit-Ledger-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}

/**
 * Generates and triggers download of Technical Approval Note PDF
 */
export function downloadApprovalNotePDF(deliverable: TaskDeliverable, approverName: string) {
  const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${deliverable.referenceNumber} - Approval Note</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; color: #172033; margin: 40px; font-size: 12px; line-height: 1.5; }
    .header { border-bottom: 2px solid #082B59; padding-bottom: 12px; margin-bottom: 20px; }
    .title { font-size: 16px; font-weight: 800; color: #082B59; margin: 0; }
    .subtitle { font-size: 11px; color: #667085; margin-top: 3px; }
    .doc-ref { float: right; text-align: right; font-family: monospace; font-size: 11px; color: #0B3B82; }
    .section-title { font-size: 12px; font-weight: 800; text-transform: uppercase; color: #082B59; border-bottom: 1px solid #CBD5E1; padding-bottom: 4px; margin-top: 20px; margin-bottom: 8px; }
    .alert-box { background: #FEF2F2; border: 1px solid #F87171; border-radius: 6px; padding: 12px; margin: 12px 0; color: #991B1B; font-size: 11px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 11px; }
    th { background: #F1F5F9; color: #334155; text-align: left; padding: 6px 8px; font-size: 10px; text-transform: uppercase; border: 1px solid #CBD5E1; }
    td { padding: 6px 8px; border: 1px solid #E2E8F0; }
    .sign-section { margin-top: 30px; border-top: 1px solid #94A3B8; padding-top: 15px; display: grid; grid-template-columns: 1fr 1fr; gap: 20px; font-size: 11px; }
    .signature-badge { font-family: monospace; font-weight: bold; color: #15803D; }
  </style>
</head>
<body>
  <div class="header">
    <div class="doc-ref">
      Ref: ${deliverable.referenceNumber}<br>
      Date: ${deliverable.generatedDate}
    </div>
    <h1 class="title">Enterprise Industrial Complex</h1>
    <div class="subtitle">Asset Integrity & Process Engineering Directorate • CDU/VDU Complex</div>
  </div>

  <h2 style="font-size: 14px; font-weight: 800; margin-bottom: 15px;">${deliverable.title}</h2>

  <div class="section-title">1. Executive Summary & Compliance Verdict</div>
  <p>${deliverable.executiveSummary}</p>

  ${deliverable.deviation ? `
  <div class="alert-box">
    <strong>CRITICAL SOP DEVIATION DETECTED:</strong> ${deliverable.deviation.parameterName}<br>
    • Observed: ${deliverable.deviation.observedValue} (Source: ${deliverable.deviation.observedSourceDoc})<br>
    • Required Limit: ${deliverable.deviation.requiredValue} (Standard: ${deliverable.deviation.requiredStandardDoc})<br>
    • Variance: ${deliverable.deviation.variance}
  </div>
  ` : ''}

  <div class="section-title">2. Mandatory SOP Comparison Table</div>
  <table>
    <thead>
      <tr>
        <th>Parameter / Criterion</th>
        <th>Observed (Report)</th>
        <th>Standard Limit</th>
        <th>Compliance</th>
      </tr>
    </thead>
    <tbody>
      ${deliverable.sopComparison.map(r => `
        <tr>
          <td><strong>${r.criterion}</strong></td>
          <td>${r.observed}</td>
          <td>${r.standard}</td>
          <td><strong style="color: ${r.compliance === 'DEVIATION' ? '#DC2626' : '#16A34A'};">${r.compliance}</strong></td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="section-title">3. Recommended Action & Engineering Directive</div>
  <p>${deliverable.recommendation}</p>

  <div class="sign-section">
    <div>
      <strong>Prepared By:</strong><br>
      Rajesh Kumar (Plant / Process Engineer)<br>
      Process Engineering Directorate Cell
    </div>
    <div>
      <strong>Approved By:</strong><br>
      ${deliverable.approvedBy || approverName}<br>
      <span class="signature-badge">✓ Digital RSA Signature: ${deliverable.digitalSignature || 'SIG_RSA4096_DR_SHETTY_Enterprise_EXEC'}</span>
    </div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 400);
    }
  </script>
</body>
</html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
  } else {
    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${deliverable.referenceNumber.replace(/\//g, '_')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}

/**
 * Pure client-side PDF Blob generator for the Demo Sample Inspection Report (Shot 2)
 */
export function downloadSampleInspectionReportPDF() {
  const title = "NON-DESTRUCTIVE TESTING (NDT) INSPECTION REPORT";
  const subtitle = "SovereignForge Industrial Compliance Asset Management";
  const lines = [
    "========================================================================================",
    "DOCUMENT ID: INSP/2026/HX-204-Q3 | DATE: 15-JUN-2026 | CLASSIFICATION: CONFIDENTIAL",
    "EQUIPMENT TARGET: CDU-03 COMPLEX - HEAT EXCHANGER HX-204 (SHELL & TUBE)",
    "INSPECTION METHOD: ULTRASONIC NDT THICKNESS SURVEY (ASME SECTION V)",
    "========================================================================================",
    "",
    "1. EXECUTIVE MEASUREMENT SUMMARY:",
    "- Equipment Nominal Design Thickness: 12.5 mm (ASME Section VIII Div 1)",
    "- Statutory Minimum Retirement Thickness: 7.8 mm (SOP-4.2.1 Section 6.1)",
    "- Minimum Measured Wall Thickness: 8.2 mm (Location: Nozzle N2 vicinity, Grid C4)",
    "- Calculated Historical Corrosion Rate: 0.28 mm/year",
    "- Calculated Remaining Service Life: 1.43 Years (approx. 17 months)",
    "",
    "2. ULTRASONIC THICKNESS GRID MEASUREMENTS:",
    "Grid A1: 10.4 mm | Grid A2: 10.1 mm | Grid A3: 9.8 mm",
    "Grid B1: 9.5 mm  | Grid B2: 9.2 mm  | Grid B3: 8.9 mm",
    "Grid C1: 8.8 mm  | Grid C2: 8.5 mm  | Grid C4 (Nozzle N2): 8.2 mm [CRITICAL THINNING]",
    "",
    "3. FIELD NDT RECOMMENDATION (NON-CONFORMANCE DETECTED):",
    "- Field inspector suggests deferring turnaround to 18 months (March 2028).",
    "- WARNING: SOP-4.2.1 Section 7.1 strictly limits turnaround deferral to 12 months for sour crude service.",
    "- Mandatory Action: Advance turnaround window to Q1 2027 to prevent containment breach.",
    "",
    "REPORT SIGN-OFF: NDT Level-III Inspector Rajesh Kumar | Certified ISO-9712"
  ];

  let streamContent = 'BT\n/F1 14 Tf\n50 750 Td\n(' + title + ') Tj\nET\n';
  streamContent += 'BT\n/F1 10 Tf\n50 732 Td\n(' + subtitle + ') Tj\nET\n';
  
  let y = 700;
  for (const line of lines) {
    const safeLine = line.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
    streamContent += `BT\n/F1 9 Tf\n50 ${y} Td\n(${safeLine}) Tj\nET\n`;
    y -= 15;
  }

  const streamLen = streamContent.length;

  let pdfData = '%PDF-1.4\n';
  const offsets: number[] = [];

  // Obj 1
  offsets.push(pdfData.length);
  pdfData += '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n';

  // Obj 2
  offsets.push(pdfData.length);
  pdfData += '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n';

  // Obj 3
  offsets.push(pdfData.length);
  pdfData += '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n';

  // Obj 4
  offsets.push(pdfData.length);
  pdfData += `4 0 obj\n<< /Length ${streamLen} >>\nstream\n${streamContent}\nendstream\nendobj\n`;

  // Obj 5
  offsets.push(pdfData.length);
  pdfData += '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n';

  // XRef
  const xrefOffset = pdfData.length;
  pdfData += 'xref\n0 6\n0000000000 65535 f \n';
  for (const off of offsets) {
    pdfData += off.toString().padStart(10, '0') + ' 00000 n \n';
  }

  pdfData += `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  const blob = new Blob([pdfData], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'sample_inspection_report.pdf';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

