// ============================================================================
// SOVEREIGNFORGE AI - CLIENT-SIDE PDF & DELIVERABLE EXPORT ENGINE
// Generates official MRPL Industrial Compliance PDFs & Signed Reports
// ============================================================================

import { AuditEvent, TaskDeliverable } from '../types';

/**
 * Generates and triggers download of a printable, high-fidelity MRPL PDF / HTML Report
 */
export function downloadAuditLedgerPDF(logs: AuditEvent[], userName: string) {
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
  const auditId = `MRPL-AUD-EXPORT-${Date.now()}`;
  
  const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>MRPL Forensic Audit Ledger - ${auditId}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; color: #172033; margin: 30px; font-size: 11px; }
    .header { border-bottom: 2px solid #082B59; padding-bottom: 12px; margin-bottom: 16px; }
    .title { font-size: 16px; font-weight: 800; color: #082B59; margin: 0; }
    .subtitle { font-size: 10px; color: #667085; margin-top: 2px; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; margin-bottom: 16px; background: #F8FAFC; padding: 10px; border-radius: 6px; border: 1px solid #E2E8F0; }
    .meta-item strong { display: block; font-size: 9px; text-transform: uppercase; color: #64748B; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 10px; }
    th { background: #0B3B82; color: white; text-align: left; padding: 6px 8px; font-size: 9px; text-transform: uppercase; }
    td { padding: 6px 8px; border-bottom: 1px solid #E2E8F0; }
    tr:nth-child(even) { background: #F8FAFC; }
    .status-badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-weight: 700; font-size: 9px; }
    .status-success { background: #DCFCE7; color: #166534; }
    .status-blocked { background: #FEE2E2; color: #991B1B; }
    .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #CBD5E1; font-size: 9px; color: #64748B; display: flex; justify-content: space-between; }
    .hash { font-family: monospace; font-size: 9px; color: #0B3B82; word-break: break-all; }
  </style>
</head>
<body>
  <div class="header">
    <h1 class="title">MANGALORE REFINERY AND PETROCHEMICALS LIMITED (MRPL)</h1>
    <div class="subtitle">SovereignForge AI — On-Premise Air-Gapped Forensic Audit Ledger</div>
  </div>

  <div class="meta-grid">
    <div class="meta-item">
      <strong>Generated By</strong>
      ${userName} (SOC Operator)
    </div>
    <div class="meta-item">
      <strong>Export Timestamp</strong>
      ${timestamp}
    </div>
    <div class="meta-item">
      <strong>Perimeter Status</strong>
      AIR-GAP ACTIVE (Zero Egress)
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Timestamp & Audit ID</th>
        <th>User / Principal</th>
        <th>Action</th>
        <th>Resource / Target</th>
        <th>Agent</th>
        <th>Result</th>
        <th>Risk</th>
      </tr>
    </thead>
    <tbody>
      ${logs.map(l => `
        <tr>
          <td><strong>${l.timestamp}</strong><br><span style="color:#2563EB;">${l.auditId}</span></td>
          <td>${l.user}</td>
          <td><code>${l.action}</code></td>
          <td>${l.resource}</td>
          <td>${l.agent}</td>
          <td><span class="status-badge ${l.result === 'SUCCESS' ? 'status-success' : 'status-blocked'}">${l.result}</span></td>
          <td>${l.risk}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    <div>
      <strong>Cryptographic Ledger Signature:</strong><br>
      <span class="hash">SHA256: 7f8a9b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcd</span>
    </div>
    <div style="text-align: right;">
      MRPL Cyber Security & Regulatory Compliance Directorate<br>
      Confidential — Internal Use Only
    </div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 400);
    }
  </script>
</body>
</html>
  `;

  // Open in printable pop-up for immediate direct PDF generation / print save
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
  } else {
    // Fallback: trigger HTML/Text download
    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MRPL-Forensic-Audit-Ledger-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}

/**
 * Generates and triggers download of Technical Approval Note PDF
 */
export function downloadApprovalNotePDF(deliverable: TaskDeliverable, approverName: string) {
  const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${deliverable.referenceNumber} - Approval Note</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; color: #172033; margin: 40px; font-size: 12px; line-height: 1.5; }
    .header { border-bottom: 2px solid #082B59; padding-bottom: 12px; margin-bottom: 20px; }
    .title { font-size: 16px; font-weight: 800; color: #082B59; margin: 0; }
    .subtitle { font-size: 11px; color: #667085; margin-top: 3px; }
    .doc-ref { float: right; text-align: right; font-family: monospace; font-size: 11px; color: #0B3B82; }
    .section-title { font-size: 12px; font-weight: 800; text-transform: uppercase; color: #082B59; border-bottom: 1px solid #CBD5E1; padding-bottom: 4px; margin-top: 20px; margin-bottom: 8px; }
    .alert-box { background: #FEF2F2; border: 1px solid #F87171; border-radius: 6px; padding: 12px; margin: 12px 0; color: #991B1B; font-size: 11px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 11px; }
    th { background: #F1F5F9; color: #334155; text-align: left; padding: 6px 8px; font-size: 10px; text-transform: uppercase; border: 1px solid #CBD5E1; }
    td { padding: 6px 8px; border: 1px solid #E2E8F0; }
    .sign-section { margin-top: 30px; border-top: 1px solid #94A3B8; padding-top: 15px; display: grid; grid-template-columns: 1fr 1fr; gap: 20px; font-size: 11px; }
    .signature-badge { font-family: monospace; font-weight: bold; color: #15803D; }
  </style>
</head>
<body>
  <div class="header">
    <div class="doc-ref">
      Ref: ${deliverable.referenceNumber}<br>
      Date: ${deliverable.generatedDate}
    </div>
    <h1 class="title">MANGALORE REFINERY AND PETROCHEMICALS LIMITED</h1>
    <div class="subtitle">Asset Integrity & Process Engineering Directorate • CDU/VDU Complex</div>
  </div>

  <h2 style="font-size: 14px; font-weight: 800; margin-bottom: 15px;">${deliverable.title}</h2>

  <div class="section-title">1. Executive Summary & Compliance Verdict</div>
  <p>${deliverable.executiveSummary}</p>

  ${deliverable.deviation ? `
  <div class="alert-box">
    <strong>CRITICAL SOP DEVIATION DETECTED:</strong> ${deliverable.deviation.parameterName}<br>
    • Observed: ${deliverable.deviation.observedValue} (Source: ${deliverable.deviation.observedSourceDoc})<br>
    • Required Limit: ${deliverable.deviation.requiredValue} (Standard: ${deliverable.deviation.requiredStandardDoc})<br>
    • Variance: ${deliverable.deviation.variance}
  </div>
  ` : ''}

  <div class="section-title">2. Mandatory SOP Comparison Table</div>
  <table>
    <thead>
      <tr>
        <th>Parameter / Criterion</th>
        <th>Observed (Report)</th>
        <th>Standard Limit</th>
        <th>Compliance</th>
      </tr>
    </thead>
    <tbody>
      ${deliverable.sopComparison.map(r => `
        <tr>
          <td><strong>${r.criterion}</strong></td>
          <td>${r.observed}</td>
          <td>${r.standard}</td>
          <td><strong style="color: ${r.compliance === 'DEVIATION' ? '#DC2626' : '#16A34A'};">${r.compliance}</strong></td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="section-title">3. Recommended Action & Engineering Directive</div>
  <p>${deliverable.recommendation}</p>

  <div class="sign-section">
    <div>
      <strong>Prepared By:</strong><br>
      Rajesh Kumar (Plant / Process Engineer)<br>
      MRPL Process Engineering Cell
    </div>
    <div>
      <strong>Approved By:</strong><br>
      ${deliverable.approvedBy || approverName}<br>
      <span class="signature-badge">✓ Digital RSA Signature: ${deliverable.digitalSignature || 'SIG_RSA4096_DR_SHETTY_MRPL_EXEC'}</span>
    </div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 400);
    }
  </script>
</body>
</html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
  } else {
    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${deliverable.referenceNumber.replace(/\//g, '_')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}
